name: funfono_backend
description: Backend para o aplicativo FunFono usando Dart Frog
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dart_frog: ^1.1.0
  postgres: ^2.5.0
  crypto: ^3.0.0
  uuid: ^3.0.0
  dotenv: ^3.0.0
  json_annotation: ^4.9.0
  logger: ^2.0.0
  build_runner: ^2.4.15
  mailer: ^6.1.0 

dev_dependencies:
  test: ^1.24.0
  json_serializable: ^6.7.1
  dart_frog_gen: ^1.1.0